### ISSUE TITLE
Delivery slot is not coming in on_confirm  api.

### ISSUE THREAD

**Issue by mukulsirohi-qa** [Open-network-for-digital-commerce/Pre-production#23]
**from Buyer app: Kotak**

There is no option to provide delivery slot to customer as that is not coming in on_confirm  api.

**Comment by BLR-0118** [comment]
Pls post logs

**Comment by mukulsirohi-qa** [comment]
For On_Confirm:

As per document: ONDC Transaction Contract between Retail Buyer and Seller

We should get Delivery time as:


Response:
{
    "context": {
        "domain": "nic2004:52110",
        "country": "IND",
        "city": "std:011",
        "action": "on_confirm",
        "bppUri": "https://null/confirm",
        "transactionId": "tt1989897872022290771",
        "timestamp": "2022-07-29T15:39:42.433103",
        "key": "MCowBQYDK2VuAyEAZEI6HvCthb67jqZsOZkhnmoacUlV2ZNmsr45Rgm6PwA="
    },
    "message": {
        "order": [
            {
                "id": "464",
                "state": "Active",
                "items": [
                    {
                        "id": "10",
                        "quantity": {
                            "count": 1,
                            "measure": null,
                            "selected": null
                        },
                        "parentItemId": null,
                        "descriptor": null,
                        "price": null,
                        "categoryId": null,
                        "time": null,
                        "tags": null,
                        "provider": null,
                        "location_id": null,
                        "bpp_id": null
                    }
                ],
                "billing": {
                    "name": "mohit gupta",
                    "organization": null,
                    "address": {
                        "door": "Indrapuram",
                        "name": "mohit gupta",
                        "locality": "delhi nehru place",
                        "city": "Ghaziabad",
                        "state": "delhi",
                        "country": "",
                        "sameAsDelivery": false
                    },
                    "email": "mohit.bindal16@gmail.com",
                    "phone": "9089898989",
                    "time": null,
                    "taxNumber": null,
                    "created_at": "2022-07-27T13:15:43",
                    "updated_at": "2022-07-27T13:15:43"
                },
                "fulfillment": {
                    "id": null,
                    "type": "Delivery",
                    "providerId": null,
                    "state": null,
                    "tracking": false,
                    "customer": null,
                    "agent": null,
                    "vehicle": null,
                    "start": {
                        "location": {
                            "id": "10",
                            "descriptor": {
                                "name": "10",
                                "code": null,
                                "symbol": null,
                                "images": null,
                                "audio": null,
                                "short_desc": null,
                                "long_desc": null,
                                "3d_render": null
                            },
                            "gps": "28.50526, 77.19743",
                            "address": null,
                            "stationCode": null,
                            "city": null,
                            "country": null,
                            "circle": null,
                            "polygon": null,
                            "time": null,
                            "3dspace": null
                        },
                        "time": null,
                        "instructions": null,
                        "contact": {
                            "phone": "9089898989",
                            "email": "mohit.bindal16@gmail.com",
                            "tags": null
                        },
                        "person": null
                    },
                    "end": {
                        "location": {
                            "id": null,
                            "descriptor": null,
                            "gps": "28.50526,77.19743",
                            "address": {
                                "door": "Indrapuram",
                                "name": "mohit gupta",
                                "locality": "delhi nehru place",
                                "city": "Ghaziabad",
                                "state": "delhi",
                                "country": "",
                                "sameAsDelivery": false
                            },
                            "stationCode": null,
                            "city": null,
                            "country": null,
                            "circle": null,
                            "polygon": null,
                            "time": null,
                            "3dspace": null
                        },
                        "time": null,
                        "instructions": null,
                        "contact": {
                            "phone": "9089898989",
                            "email": null,
                            "tags": null
                        },
                        "person": null
                    },
                    "tags": null
                },
                "payment": {
                    "type": "ON-ORDER",
                    "status": "paid",
                    "collected_by": "BAP",
                    "collected_by_status": "Agree"
                },
                "provider": {
                    "id": "3",
                    "descriptor": null,
                    "categoryId": null,
                    "time": null,
                    "categories": null,
                    "fulfillments": null,
                    "payments": null,
                    "locations": [
                        {
                            "id": "pooja_stores_location",
                            "descriptor": null,
                            "gps": null,
                            "address": null,
                            "stationCode": null,
                            "city": null,
                            "country": null,
                            "circle": null,
                            "polygon": null,
                            "time": null,
                            "3dspace": null
                        }
                    ],
                    "offers": null,
                    "items": null,
                    "exp": null,
                    "tags": null,
                    "ttl": null,
                    "rating": null,
                    "@ondc/org/fssai_license_no": null
                },
                "created_at": "2022-07-29T15:39:42.434740",
                "updated_at": "2022-07-29T15:39:42.434755"
            }
        ]
    }
}

**Comment by BLR-0118** [comment]
Delivery slot (currently mandatory) in /on_confirm will be made optional and will be updated through /on_update. This is because the logistics provider will not be in position to provide delivery slot at the time of order confirmation but will subsequently update when "ready to ship" is triggered.
