### ISSUE TITLE
Right now there is no support to cancel Partial order.

### ISSUE THREAD

**Issue by mukulsirohi-qa** [Open-network-for-digital-commerce/Pre-production#24]
**from Buyer app: Kotak**

If someone wants to cancel any product from the order. Right now there is no option in any api to cancel partial order.

**Comment by BLR-0118** [comment]
Pls post logs

**Comment by mukulsirohi-qa** [comment]
As per document: ONDC Transaction Contract between Retail Buyer and Seller

**There is no support for partial order cancellation:**

Mandatory attributes listed below with sample values (note: cancellation flow & reason codes are defined [here](https://docs.google.com/document/d/1M-lZSduYMFKIk1V6d8QLt-j-16-rVzYVdPn0pmbkclk/edit))
{
  "context":
  {
    "domain": "nic2004:52110",
    "country": "IND",
    "city": "std:080",
    "action": "cancel",
    "core_version": "1.0.0",
    "bap_id": "ondc.paytm.com",
    "bap_uri": "https://ondc.paytm.com/retail",
    "bpp_id": "ondc.gofrugal.com/ondc/18275",
    "bpp_uri": "https://ondc.gofrugal.com/ondc/seller/adaptor",
    "transaction_id": "9fdb667c-76c6-456a-9742-ba9caa5eb765",
    "message_id": "1652092268191",
    "timestamp": "2022-06-13T07:22:45.363Z"
  },
  "message":
  {
    "order_id": "a912e-244c-4954-b74d-5be678940ec4_87",
    "[cancellation_reason_id](https://docs.google.com/document/d/1M-lZSduYMFKIk1V6d8QLt-j-16-rVzYVdPn0pmbkclk/edit)": "004"
  }
}

Note: /cancel should only be used for Order cancellation and can be initiated only if Order.state is “Created”, “Packed” or “Shipped”

**/on_cancel payload**
Mandatory attributes listed below with sample values
{
  "context":
  {
    "domain": "nic2004:52110",
    "country": "IND",
    "city": "std:080",
    "action": "on_cancel",
    "core_version": "1.0.0",
    "bap_id": "ondc.paytm.com",
    "bap_uri": "https://ondc.paytm.com/retail",
    "bpp_id": "ondc.gofrugal.com/ondc/18275",
    "bpp_uri": "https://ondc.gofrugal.com/ondc/seller/adaptor",
    "transaction_id": "9fdb667c-76c6-456a-9742-ba9caa5eb765",
    "message_id": "1652092268191",
    "timestamp": "2022-06-13T07:22:45.363Z"
  },
  "message":
  {
    "order":
    {
      “id”: "0799f385-5043-4848-8433-4643ad511a14",
      “state”: "Cancelled"
      “tags”:
      {
	“cancelled_by”: “logistics-provider”
      }
    }
  }
}

Note: 
if Order.state is not “Created”, “Packed” or “Shipped”, return NACK;
If cancellation_reason_id is not valid, return NACK;

**Comment by BLR-0118** [comment]
partial cancel of order will be through the /update API. Pls check the retail contract for this carefully.
