### ISSUE TITLE
Order status Audit trail option is not available. 

### ISSUE THREAD

**Issue by mukulsirohi-qa** [Open-network-for-digital-commerce/Pre-production#25]
**from Buyer app: Kotak**

As per document:

https://docs.google.com/document/d/1OZaKniGywLPsBC0IsT7V0gfY876HbQZqrfVTEQ6tWG4/edit

Order status Audit trail option is not available. 

BLR-0118

**Comment by BLR-0118** [comment]
Latest status will be maintained in the Order object and communicated to the other participant(s) through the protocol. Audit trail for order status should be maintained by participants. Not sure what this issue is for?
