### ISSUE TITLE
There is no support to upload images in case return flow – Which is a mandate from ONDC for launch

### ISSUE THREAD

**Issue by mukulsirohi-qa** [Open-network-for-digital-commerce/Pre-production#26]
from Buyer app: Kotak

In document:

https://docs.google.com/document/d/1M-lZSduYMFKIk1V6d8QLt-j-16-rVzYVdPn0pmbkclk/edit

For update payload there is no option to upload image, where as in document "https://docs.google.com/document/d/1M-lZSduYMFKIk1V6d8QLt-j-16-rVzYVdPn0pmbkclk/edit" it is mentioned under 3 point b 2nd para:

**/cancel payload**

/update payload - for return flow
Mandatory attributes listed below with sample values (note: return flow is defined [here](https://docs.google.com/document/d/1M-lZSduYMFKIk1V6d8QLt-j-16-rVzYVdPn0pmbkclk/edit))
{
  "context":
  {
    "domain": "nic2004:52110",
    "country": "IND",
    "city": "std:080",
    "action": "update",
    "core_version": "1.0.0",
    "bap_id": "ondc.paytm.com",
    "bap_uri": "https://ondc.paytm.com/retail",
    "bpp_id": "ondc.gofrugal.com/ondc/18275",
    "bpp_uri": "https://ondc.gofrugal.com/ondc/seller/adaptor",
    "transaction_id": "9fdb667c-76c6-456a-9742-ba9caa5eb765",
    "message_id": "1652092268191",
    "timestamp": "2022-06-13T07:22:45.363Z"
  },
  "message":
  {
    "update_target": "item",
    "order":
    {
      "id": "0799f385-5043-4848-8433-4643ad511a14",
      “state”: “Delivered”,
      "provider":
      {
        "id": "18275-ONDC-1-11094",
        “locations”:
        [
  	     {
  		     “id”: “GFFBRTFR1649830006"
  	     }
        ]
      },
      "items":
      [
        {
          "id": "18275-ONDC-1-9",
          "quantity":
          {
            "count": 1
          },
          "tags":
          {
            "return": "yes",
            "reason_code": "003",
            "status": "Return initiated",
            "ttl_approval": "PT24H",
            "ttl_reverseqc": "PT3D",
            "image": ""https://gf-ig-integration-qa-c0nn3c7.s3.amazonaws.com/images/5458
            /5458_OrderEasy_3_1639793053567.png"
          }
        }
      ]
      "fulfillments":
      [
{
          	 “id”: “Fulfillment1”,
"state":
{
"descriptor":
{
"name": "Cancelled",
}
},
"tags":
{
	“cancellation_reason_id”: “004” 
},
},
      ],
      "payment":
      {
"@ondc/org/settlement_details":
[
{
"settlement_counterparty": "buyer",
"settlement_phase": "refund",
“settlement_type”:”upi”
“settlement_amount”:”1000”
“settlement_timestamp”:”2022-07-28T18:01:53.000Z”
}
]
      }
    }
  }
}

BLR-0118

**Comment by BLR-0118** [comment]
There is an option to add images in [/update](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit) for return flow. It's also in the payload shared above. Not sure what this issue is for?
