### ISSUE TITLE
USHOP - Compliance check errors

### ISSUE THREAD

**Issue by BLR-0118** [Open-network-for-digital-commerce/Pre-production#37]
1. on_search shows items.location_id of "el" which doesn't match locations.id - what is this location then?
2. what does fulfillment_id of "Grocery" mean?
3. Catalog item.price should also have maximum_value
4. There are up to 12 images per item. Paytm may not render more than 3
5. on_select has item.price which has been removed
6. on_cancel requires cancellation_reason_id
7. If "returnable" for item is "true" in on_search, why are you returning error 50002 for return?
8. Do you have support for issuing unsolicited on_status and on_update calls?
9. You seem to be returning the header received from Kotak with the same timestamp. This is incorrect. 
10. Why is search for "milk" returning Dove soap, Coffee, etc.?

**Comment by BLR-0118** [comment]
@ensenterprises

**Comment by ensenterprises** [comment]
1. on_search shows items.location_id of "el" which doesn't match locations.id - what is this location then?
- updated location ID 65426587829 

2. what does fulfillment_id of "Grocery" mean?
- updated fulfillment_id=1 which means Delivery

3. Catalog item.price should also have maximum_value
- added field

4. There are up to 12 images per item. Paytm may not render more than 3
- made 3 images in response

5. on_select has item.price which has been removed
- removed this object

6. on_cancel requires cancellation_reason_id
- added cancellation_reason_id

7. If "returnable" for item is "true" in on_search, why are you returning error 50002 for return?
- Only via customer support we are accepting return

8. Do you have support for issuing unsolicited on_status and on_update calls?
- Yes we have support for these calls

9. You seem to be returning the header received from Kotak with the same timestamp. This is incorrect.
- We are updating the timestamp

10 .Why is search for "milk" returning Dove soap, Coffee, etc.?
- it comes under our searching algorithm (As in the Description it has this keyword)

@BLR-0118

**Comment by BLR-0118** [comment]
For 7:
a. If items are returnable, you'll have to acknowledge /update and send an /on_update with approval for return request;
b. You mentioned that you don't support part cancel, so the corresponding attr needs to be disabled;
I need updated logs for all the changes made above. Also want to see the /on_search for city;
@ensenterprises

**Comment by ensenterprises** [comment]
For 7:
a. If items are returnable, you'll have to acknowledge /update and send an /on_update with approval for return request;
-> we support returns via customer support and not automatically as of now. So, our products will be non returnable for ONDC and we will respond NACK and manage returns via call centre whose no is visible via support api and email/sms comms to consumer
b. You mentioned that you don't support part cancel, so the corresponding attr needs to be disabled;
-> Now we are not supporting cancellation also via ONDC, if they want to cancel they have to manage via call centre. We will be giving NACK on cancel api

Send you the PR no. 39 with updated logs.

**Comment by BLR-0118** [comment]
for 7a, b: if you support returns & cancel, you have to accept the request over the protocol. Contact details of customer call center will be available to buyer. The interface between the seller app & call center is up to you. Pls talk to the Unilever team and figure this out.
@ensenterprises

**Comment by rahulranjan000** [comment]
> for 7a, b: if you support returns & cancel, you have to accept the request over the protocol. Contact details of customer call center will be available to buyer. The interface between the seller app & call center is up to you. Pls talk to the Unilever team and figure this out. @ensenterprises

We will not be supporting returns and cancellation for now. There are technical and legal restrictions from our side.

**Comment by BLR-0118** [comment]
9. I still see the same timestamp in your Context as what's in the request. Also, ttl should be using ISO8601 durations format. Pls check spec for details
@ensenterprises

**Comment by ensenterprises** [comment]
Please check sent you the pull request #41

**Comment by BLR-0118** [comment]
what's the logic used to generate the timestamp for response?

**Comment by ensenterprises** [comment]
@BLR-0118 We are putting the current timestamp when we are responding to the request.

**Comment by BLR-0118** [comment]
Please check compliance with this sheet (specifically under the "Mandatory" column) for your catalog being sent in on_search response
@ensenterprises

**Comment by ensenterprises** [comment]
@BLR-0118 Checked and send you the log #42
