### ISSUE TITLE
Getting error code 500 on "https://buyer-app-preprod.ondc.org/"

### ISSUE THREAD

**Issue by mukulsirohi-qa** [Open-network-for-digital-commerce/Pre-production#45]
When we search any product on "https://buyer-app-preprod.ondc.org/". Getting 500 error. Screenshot attached. 
<img width="1428" alt="Screenshot 2022-08-08 at 10 49 26 PM" src="https://user-images.githubusercontent.com/70898554/183476311-1f49b177-aff2-44d3-9682-964de5cd02f9.png">
 

@BLR-0118

**Comment by BLR-0118** [comment]
The new lookup API in Pre-Prod needs to be enabled 
@navdeep710

**Comment by BLR-0118** [comment]
this is resolved
