### ISSUE TITLE
Getting NACK on /subscribe endpoint

### ISSUE THREAD

**Issue by ravicsc** [Open-network-for-digital-commerce/Pre-production#7]
{
  "context": {
    "operation": {
      "ops_no": 4
    },
    "message": {
      "request_id": "58baa06d-d90b-474c-82e5-cc623c787f25",
      "timestamp": "2022-07-13T12:27:54.101Z",
      "entity": {
        "gst": {
          "legal_entity_name": "CSC GRAMEEN eStore Private Limited",
          "business_address": "Ground and First Floor, Plot No.238, Okhla Industrial Area, Estate Phase-3, South Delhi, Delhi, 110020",
          "city_code": [
            "std:011"
          ],
          "gst_no": "07AAICC8575D1ZG"
        },
        "pan": {
          "name_as_per_pan": "CSC GRAMEEN ESTORE PRIVATE LIMITED",
          "pan_no": "AAICC8575D",
          "date_of_incorporation": "31/07/2020"
        },
        "name_of_authorised_signatory": "Subodh Mishra",
        "address_of_authorised Signatory": "238, Okhla Phase 3 Rd, Okhla Phase III, Okhla Industrial Area, New Delhi, Delhi 110020",
        "email_id": "subodh@cscegovindia.com",
        "mobile_no": 9871230717,
        "country": "IND",
        "subscriber_id": "https://stagingapi.cscestore.in/ondc",
        "callback_url": "/onboarding",
        "key_pair": {
          "signing_public_key": "GC09Kh83XFI+A/B6N4JJ7s9Kdg5vc4Y4teGy5NA/2/Y=",
          "encryption_public_key": "8zEAatCwWtOAKqV9fDsVxSOpXDzXD45USmjkNhvUbnU=",
          "valid_from": "2022-07-13T17:44:54.101Z",
          "valid_until": "2026-07-12T17:44:54.101Z"
        }
      },
      "network_participant": [
        {
          "subscriber_url": "/buyer/preprod/",
          "domain": "nic2004:52110",
          "type": "buyerApp",
          "msn": false,
          "city_code": [
            "std:080",
            "std:040",
            "std:0145"
          ]
        },
        {
          "subscriber_url": "/seller/preprod/",
          "domain": "nic2004:52110",
          "type": "sellerApp",
          "msn": false,
          "city_code": [
            "std:080",
            "std:040",
            "std:0145"
          ]
        }
      ]
    }
  }
}

**Comment by ganeshfosgen** [comment]
Correct json is :
{
  "context": {
    "operation": {
      "ops_no": 4
    }
    
  },
"message": {
      
      "entity": {
        "gst": {
          "legal_entity_name": "CSC GRAMEEN eStore Private Limited",
          "business_address": "Ground and First Floor, Plot No.238, Okhla Industrial Area, Estate Phase-3, South Delhi, Delhi, 110020",
          "city_code": [
            "std:011"
          ],
          "gst_no": "07AAICC8575D1ZG"
        },
        "pan": {
          "name_as_per_pan": "CSC GRAMEEN ESTORE PRIVATE LIMITED",
          "pan_no": "AAICC8575D",
          "date_of_incorporation": "31/07/2020"
        },
        "name_of_authorised_signatory": "Subodh Mishra",
        "address_of_authorised Signatory": "238, Okhla Phase 3 Rd, Okhla Phase III, Okhla Industrial Area, New Delhi, Delhi 110020",
        "email_id": "subodh@cscegovindia.com",
        "mobile_no": 9871230717,
        "country": "IND",
        "subscriber_id": "stagingapi.cscestore.in/ondc",
        "callback_url": "/onboarding",
        "key_pair": {
          "signing_public_key": "GC09Kh83XFI+A/B6N4JJ7s9Kdg5vc4Y4teGy5NA/2/Y=",
          "encryption_public_key": "8zEAatCwWtOAKqV9fDsVxSOpXDzXD45USmjkNhvUbnU=",
          "valid_from": "2022-07-12T17:44:54.101Z",
          "valid_until": "2026-07-12T17:44:54.101Z"
        }
      },
      "network_participant": [
        {
          "subscriber_url": "/buyer/preprod/",
          "domain": "nic2004:52110",
          "type": "buyerApp",
          "msn": false,
          "city_code": [
            "std:080",
            "std:040",
            "std:0145"
          ]
        },
        {
          "subscriber_url": "/seller/preprod/",
          "domain": "nic2004:52110",
          "type": "sellerApp",
          "msn": false,
          "city_code": [
            "std:080",
            "std:040",
            "std:0145"
          ]
        }
      ],
      "request_id": "58baa06d-d90b-474c-82e5-cc623c787f25",
       "timestamp": "2022-07-13T15:06:54.101Z"
    }
}

**Comment by ravicsc** [comment]
Hey now this error coming-

Is se check krna post krke
{
    "message": {
        "ack": {
            "status": "NACK"
        }
    },
    "error": {
        "type": "DOMAIN-ERROR",
        "code": "130",
        "path": null,
        "message": "https://stagingapi.cscestore.in/ondc : Domain verification file (ondc-site-verification.html) is not found "
    }
}

**Comment by ganeshfosgen** [comment]
Error code 130 is find the signature in ondc-site-verification.htm file.

your server path (https://stagingapi.cscestore.in/ondc/ondc-site-verification.htm)

you can generate signature using signing private key and signing message will be your request id.

For generate signature refer following site
https://ed25519.herokuapp.com/
eg:
Signing Private key : 8pPXr0Y4iwG590D9h2XJ+LAk2vXiOAVS0If7ep1FAqd9AK2I1RKLvAju6cr4g2HLfkU9yee/AAsXX1/UmsuScg==
signing Public key: fQCtiNUSi7wI7unK+INhy35FPcnnvwALF19f1JrLknI=
Message : 27baa06d-f90a-486c-85e5-cc621b787f04
Signature : BcJeNC7OWGvLKsmdSKmn43O1WNrmT4zDsH3nkAsRTCEs6C7RQ9FVEEqC+dmhUYlCiRsjGKkybQ6N5j7O0mPkBw==

ondc-site-verification.html file format is:

`
<html><head><meta
name='ondc-siteverification'
content='BcJeNC7OWGvLKsmdSKmn43O1WNrmT4zDsH3nkAsRTCEs6C7RQ9FVEEqC+dmhUYlCiRsjGKkybQ6N5j7O0mPkBw==' /></head>
<body>ONDC Site Verification
Page </body> </html>
`

**Comment by sujeets-protean** [comment]
@BLR-0118 Can we please close this as it was resolved ?
